# Generated by Django 4.2.26 on 2026-01-07 12:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_contactmessage_responded_at_contactmessage_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.validate_phone_digits]),
        ),
    ]
