# Generated by Django 4.2.26 on 2026-01-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_default_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Customer queries'},
        ),
    ]
