# Generated by Django 4.2.26 on 2025-12-12 16:14

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['title'], 'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
