# Generated by Django 4.2.26 on 2025-12-28 21:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_options_alter_story_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='origin_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
