# Generated by Django 4.2.26 on 2025-12-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_discount_amount_order_discount_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSingleUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('order_number', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.AddConstraint(
            model_name='discountsingleuse',
            constraint=models.UniqueConstraint(fields=('code', 'email'), name='unique_discount_per_email'),
        ),
    ]
