# Generated by Django 4.2.26 on 2026-01-07 12:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_discountsingleuse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[core.validators.validate_phone_digits]),
        ),
    ]
