# Generated by Django 4.2.26 on 2025-11-26 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='NutritionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(help_text='E.g. g, mg, kcal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('storage_instructions', models.TextField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=254, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Quantities',
            },
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='products.product')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.quantity')),
            ],
            options={
                'verbose_name_plural': 'Product Quantities',
                'unique_together': {('product', 'quantity')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', through='products.ProductQuantity', to='products.quantity'),
        ),
        migrations.CreateModel(
            name='NutritionLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('metric_unit', models.CharField(editable=False, max_length=15)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nutritionmetric')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_labels', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'metric')},
            },
        ),
    ]
